[2024-05-05T18:50:38.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T18:50:38.705+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-05-05T18:50:36.842346+00:00 [queued]>
[2024-05-05T18:50:38.711+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-05-05T18:50:36.842346+00:00 [queued]>
[2024-05-05T18:50:38.711+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-05T18:50:38.721+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): starting> on 2024-05-05 18:50:36.842346+00:00
[2024-05-05T18:50:38.726+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T18:50:38.727+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-05-05T18:50:38.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'starting', 'manual__2024-05-05T18:50:36.842346+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmp_p98t5i0']
[2024-05-05T18:50:38.728+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask starting
[2024-05-05T18:50:38.761+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.starting manual__2024-05-05T18:50:36.842346+00:00 [running]> on host 0d2f9ca33b23
[2024-05-05T18:50:38.824+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='starting' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T18:50:36.842346+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T18:50:36.842346+00:00'
[2024-05-05T18:50:38.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T18:50:38.826+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T18:50:38.826+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Chuẩn bị cào dữ liệu"']
[2024-05-05T18:50:38.835+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T18:50:38.837+0000] {subprocess.py:93} INFO - Chuẩn bị cào dữ liệu
[2024-05-05T18:50:38.837+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T18:50:38.838+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T18:50:38.854+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=starting, execution_date=20240505T185036, start_date=20240505T185038, end_date=20240505T185038
[2024-05-05T18:50:38.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T18:50:38.919+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-05T18:50:38.921+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
