[2024-05-05T18:40:17.257+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T18:40:17.271+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.insert_db scheduled__2024-05-05T18:36:30.089557+00:00 [queued]>
[2024-05-05T18:40:17.277+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.insert_db scheduled__2024-05-05T18:36:30.089557+00:00 [queued]>
[2024-05-05T18:40:17.277+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-05T18:40:17.287+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_db> on 2024-05-05 18:36:30.089557+00:00
[2024-05-05T18:40:17.294+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=142) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T18:40:17.295+0000] {standard_task_runner.py:63} INFO - Started process 144 to run task
[2024-05-05T18:40:17.295+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'insert_db', 'scheduled__2024-05-05T18:36:30.089557+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmps_acc9fn']
[2024-05-05T18:40:17.296+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask insert_db
[2024-05-05T18:40:17.330+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.insert_db scheduled__2024-05-05T18:36:30.089557+00:00 [running]> on host 0d2f9ca33b23
[2024-05-05T18:40:17.391+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='insert_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T18:36:30.089557+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-05T18:36:30.089557+00:00'
[2024-05-05T18:40:17.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T18:40:30.175+0000] {logging_mixin.py:188} INFO - Successfully.
[2024-05-05T18:40:30.184+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-05T18:40:30.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T18:40:30.192+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=insert_db, execution_date=20240505T183630, start_date=20240505T184017, end_date=20240505T184030
[2024-05-05T18:40:30.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T18:40:30.231+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-05T18:40:30.232+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
