[2024-05-05T18:39:00.562+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T18:39:00.582+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-05-05T18:38:56.342558+00:00 [queued]>
[2024-05-05T18:39:00.590+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-05-05T18:38:56.342558+00:00 [queued]>
[2024-05-05T18:39:00.590+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-05T18:39:00.602+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_file_task> on 2024-05-05 18:38:56.342558+00:00
[2024-05-05T18:39:00.609+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T18:39:00.611+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2024-05-05T18:39:00.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'create_file_task', 'manual__2024-05-05T18:38:56.342558+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmplnje3sw6']
[2024-05-05T18:39:00.613+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask create_file_task
[2024-05-05T18:39:00.653+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.create_file_task manual__2024-05-05T18:38:56.342558+00:00 [running]> on host 0d2f9ca33b23
[2024-05-05T18:39:00.723+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T18:38:56.342558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T18:38:56.342558+00:00'
[2024-05-05T18:39:00.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T18:39:00.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T18:39:00.725+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/dags/database.db']
[2024-05-05T18:39:00.735+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T18:39:00.739+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T18:39:00.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T18:39:00.759+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=create_file_task, execution_date=20240505T183856, start_date=20240505T183900, end_date=20240505T183900
[2024-05-05T18:39:00.785+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T18:39:00.808+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T18:39:00.810+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
