[2024-04-28T16:07:11.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T16:07:11.613+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.insert_db manual__2024-04-28T16:06:30.964075+00:00 [queued]>
[2024-04-28T16:07:11.620+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.insert_db manual__2024-04-28T16:06:30.964075+00:00 [queued]>
[2024-04-28T16:07:11.620+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-28T16:07:11.633+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_db> on 2024-04-28 16:06:30.964075+00:00
[2024-04-28T16:07:11.640+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T16:07:11.642+0000] {standard_task_runner.py:63} INFO - Started process 116 to run task
[2024-04-28T16:07:11.642+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'insert_db', 'manual__2024-04-28T16:06:30.964075+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmp0nqhtlh9']
[2024-04-28T16:07:11.643+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask insert_db
[2024-04-28T16:07:11.676+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.insert_db manual__2024-04-28T16:06:30.964075+00:00 [running]> on host 73ada3aeb297
[2024-04-28T16:07:11.742+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='insert_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T16:06:30.964075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T16:06:30.964075+00:00'
[2024-04-28T16:07:11.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T16:08:03.461+0000] {logging_mixin.py:188} INFO - Successfully.
[2024-04-28T16:08:03.476+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-28T16:08:03.476+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T16:08:03.484+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=insert_db, execution_date=20240428T160630, start_date=20240428T160711, end_date=20240428T160803
[2024-04-28T16:08:03.530+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T16:08:03.549+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-28T16:08:03.550+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
